import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const employees = [
  "Emma",
  "Naya",
  "Gilla",
  "Arbaya",
  "Kirsten",
  "Donna",
  "Lexi",
];

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <nav className="w-full">
        <ul className="flex w-full justify-center">
          {employees.map((emp, index) => {
            return (
                <li key={emp + index} className="flex-grow">
                  <Button className="w-full">{emp}</Button>
                </li>
            );
          })}
        </ul>
      </nav>
      {children}
      </body>
      </html>
  );
}
